spring:
  config:
    import: optional:configserver:,configtree:/workspace/secrets/*/
  cloud:
    config:
      uri: http://configuration-service
  rabbitmq:
    host: rabbitmq
  redis:
    host: redis